### ISSUE TITLE
I'd love to see a README!

### ISSUE THREAD

**Issue by gonzalo-bulnes** [tmayr/acid-forecast#1]
Hi @tmayr, could you please write a README file?

**Comment by tmayr** [comment]
Haha sure thing, I'll update it in a bit!

**Comment by tmayr** [comment]
@gonzalo-bulnes Is it better now?

Cheers!

**Comment by gonzalo-bulnes** [comment]
Nice. I like it. 

Cheers!

**Comment by tmayr** [comment]
Cool!
